### ISSUE TITLE
File /snipeitapp_config.php not found in server (docker)

### ISSUE THREAD

**Issue by SonGokussj4** [diegogarciadev/android_snipeitapp_config#26]
Hello, trying to make your app work but have some problems

**Describe the bug**
When I try to configure the APP, it keeps saying `File /snipeitapp_config.php not found in server, review previous steps`

**To Reproduce**
I've set up snipeit as docker with docker-compose (seen bellow) and Traefik as reverse proxy. It runs well on it's own.

I'm copying the file into containers `/var/www/html/public/snipeitapp_config.php`  <-- Is this correct?

```yml
version: "3"

networks:
  traefik:
    external: true

services:
  
  mysql:
    image: linuxserver/mariadb
    ...
    networks:
      - traefik
  
  snipeit:
    image: linuxserver/snipe-it:latest
    ...
    volumes:
      - ./app_data:/config
      - ./public:/var/www/html/public  <- I've added this to input snipeitapp_config.php into
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend=snipeit"
    ports:
      - "9999:80"
    networks:
      - traefik
```

Now the thing is:
  - If I visit URL `http://<SERVER>:9999/snipeitapp_config.php` in **PC browser**, it gives me back the `{"api_key": "xxxxx"}` response.
  - If I visit URL `http://<SERVER>:9999/snipeitapp_config.php` in **MOBILE browser**, it gives me back the `{"api_key": "xxxxx"}` response. (so no problem with device)
  - If I input this exact URL into the mobile config field (even manually add api_key to the _User an alternative method_, it flashes the error message.

Not sure what the problem could be.

**Smartphone:**
 - Device: Sony Xperia 5 II
 - OS: Android 11
 - Browser: Chrome
